version: '{build}'

-
  image: Visual Studio 2017
  configuration:
  - Release
  before_build:
  - ps: nuget restore Source\Svg.csproj
  - ps: nuget restore Tests\Svg.UnitTests\Svg.UnitTests.csproj
  build:
    project: Source\Svg.sln

-
  image: ubuntu
  configuration:
  - Release
  before_build:
  - ps: dotnet restore Source\Svg.csproj
  - ps: dotnet restore Tests\Svg.UnitTests\Svg.UnitTests.csproj
  build:
    project: Tests\Svg.UnitTests\Svg.UnitTests.csproj
